### ISSUE TITLE
After plugin activation template caching is not working anymore

### ISSUE THREAD

**Issue by Cu8eeeR** [zingaburga/XThreads-MyBB-Plugin#12]
After plugin activation template caching is not working anymore. All templates are loaded every time, caching is broken. 

MyBB 1.8.10, php 7.0.10

**Comment by zingaburga** [comment]
I presume that [url=http://mybbhacks.zingaburga.com/showthread.php?tid=288&pid=20436#pid20436]you also posted here[/url]?

If so, does this commit deal with your issue? https://github.com/zingaburga/XThreads-MyBB-Plugin/commit/240713f905a8ca8df4eed8fe98dcf16155a39f7a

**Comment by Cu8eeeR** [comment]
@zingaburga - hi, thank you for your reply! I will try ASAP (in 8 hours).

Rin editor issue: - https://github.com/martec/Rin-Editor/issues/15
Template caching issue: I will provide you more info. When you open the debugg window and XThreads is activated, number of cached templates is 0; when you disable XThreads (not uninstall) number of cached templates are 90 for example (all of them are loaded from cache).

**Comment by Cu8eeeR** [comment]
Issue related to Rin editor is fixed! Thank you very much my friend! Amazing plugin!
