### ISSUE TITLE
Checkboxes - when you leave it empty, the previous value is saved

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#13]
If you select one or more values in checkboxes (and this field is not required) -> save the post (thread) -> edit this post and leave this checkboxes unselected (no value selected) -> save -> check the post - the previous values are still there... :(

@zingaburga

**Comment by zingaburga** [comment]
Thanks for reporting the issue and sorry for the late reply.

I've fixed this bug in my local repo and should have the changes pushed up soon.

**Comment by Eldenroot** [comment]
Thank you for your time and great support!

**Comment by zingaburga** [comment]
No worries.

Note, is you want to apply these fixes, you'll also need XThreads to re-generate cache/xthreads_evalcache.php - this can be done simply by editing a thread field and saving it without any changes.
