### ISSUE TITLE
Content is deleted when you use "new line" in title html tag

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#14]
OK, I found a weird bug. When you put `title="TEXT &#013; TEXTNEXTLINE"` or `title="TEXT &lt;br&gt; TEXTNEXTLINE`" in html - for example:

This "bug" occurs in formatting mapping list:
value: `BLACK`
displayed output: `<div title="CZE: Černá &lt;br&gt; ENG: Black &lt;br&gt; DE: Schwarz" class="mp_black"></div>`

When you save this it works fine and the content is displayed correctly, but when you wanna edit this custom field in ACP and save it again, the whole content is lost (all content after `&lt;br&gt;`) in formatting mapping list. There should be at least any warning if it cannot be fixed.

Thank you very much!

**Comment by zingaburga** [comment]
Sorry for the late reply and thanks for reporting the issue.

Unfortunately I haven't been able to reproduce.  I created a new field, entered a name and key, then added the above to the Format Map List.  I then saved the field, and went back in, but the text in the Format Map List hadn't changed.  I did also try saving again, but that didn't make a difference.

**Comment by Eldenroot** [comment]
Hmm, did you try to change anything else for that field and save it again? I put the code above into formatting mapping list.

**Comment by zingaburga** [comment]
Yes.

Are you able to get the HTML output on the broken ACP page?

**Comment by Eldenroot** [comment]
ACP page is not broken, the text is just stripped out (everything after the "new line" html tag)

**Comment by zingaburga** [comment]
Okay, can you get me the HTML output of the textbox on the ACP page?

**Comment by Eldenroot** [comment]
@zingaburga - I am sorry for my late reply, quite busy lately and I missed notification email for this ticket.

The whole content after '&lt;br&gt;' is lost when you update the thread field setting in ACP.

**Comment by zingaburga** [comment]
You've already said that before, but unfortunately I cannot help you unless you can provide me with the requested info in my previous comment.

**Comment by Eldenroot** [comment]
I am sorry, but I dont know what causes this issue. I described it in my first post.
