### ISSUE TITLE
Custom WOL Text - text is displayed in profiles but no link or name of the thread

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#15]
Custom WOL Text - text is displayed in profiles but no link or name of the thread

**Comment by zingaburga** [comment]
Sorry for the late reply and thanks for reporting the issue.

Unfortunately I haven't been able to reproduce.  Are you able to give more details, such as MyBB version, the text used and which WOL text you overwrote?

**Comment by Eldenroot** [comment]
When the use is browsing a thread -> this is displayed in his profile - 
![image](https://user-images.githubusercontent.com/778890/40888623-1496fe00-675a-11e8-8ac4-cf110caac5b2.png)

however when you set your custom text for Xthreads, there is no link, time, and name of the thread displayed... just "Reading thread"

**Comment by zingaburga** [comment]
Works fine here:
![clipboard01](https://user-images.githubusercontent.com/430322/40909792-fc235028-67d9-11e8-95ed-86425f94bcf5.png)

> Are you able to give more details, such as MyBB version, the text used and which WOL text you overwrote?

In particular, did you omit `<a href="{1}">{2}</a> {3}` from your text?

**Comment by Eldenroot** [comment]
OK, well maybe thats my issue :(

**Comment by Eldenroot** [comment]
OK, finally found free time - it is because of that, working fine, thank you!
