### ISSUE TITLE
XThreads - Warning [2] Declaration of _objcont_2::execute_thread_moderation

### ISSUE THREAD

**Issue by Axboard** [zingaburga/XThreads-MyBB-Plugin#16]
<img width="1437" alt="zrzut ekranu 2018-08-29 o 21 20 15" src="https://user-images.githubusercontent.com/42621417/45144186-b47fa680-b1bd-11e8-855a-cdee6d38b890.png">
After upgrading to version 1.8.18, I get this error using the custom moderator tools in the place where I use XThreads.

**Comment by zingaburga** [comment]
Thanks for bringing that up.  
I haven't done any testing, but from looking at the code, it's probably fixable by editing inc/xthreads/xt_modupdhooks.php, replacing:

    function execute_thread_moderation($thread_options, $tids) {

with

    function execute_thread_moderation($thread_options=array(), $tids=array()) {

Does that work for you?

**Comment by Axboard** [comment]
Thank you, your tip solved the problem.

**Comment by zingaburga** [comment]
Thanks for the confirmation!
