### ISSUE TITLE
Add new feature - different output option for usergroups

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#17]
Would be nice to have a new option for every custom field - something like:

------------------------
Display output for selected usegroups:
- usergroups selection box
- display output field
Display output for the rest usergroups (not selected usegroups from the setting above).
-display output field
------------------------

**Comment by zingaburga** [comment]
This already exists? It's called **Unviewable Value**, which shows if you select anything from the **Viewable by Usergroups** list.

**Comment by Eldenroot** [comment]
You are right of course! I am sorry, missed that (now I dont need to add another if statement in templates)
