### ISSUE TITLE
Delete button for attachments is not working

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#22]
MyBB 1.8.22 - Delete button is not working anymore... maybe AJAX issue?

**Comment by zingaburga** [comment]
Which delete button are you referring to?  
The "Remove" button next to MyBB's attachments when editing a post?

I did a quick test with removing MyBB attachments, XThreads attachments, and even the quick delete post button, but they all seem to work for me.  
Perhaps try opening the developer console in your browser (F12 key) before attempting a delete, and see what Javascript error it logs when you try to delete.
