### ISSUE TITLE
Add New Forum Error

### ISSUE THREAD

**Issue by h2kyaw** [zingaburga/XThreads-MyBB-Plugin#25]
I got below error after I create new Forum at mybbb.

> MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1364 - Field 'xthreads_tplprefix' doesn't have a default value
Query:
INSERT INTO p_forums (`name`,`description`,`linkto`,`type`,`pid`,`parentlist`,`disporder`,`active`,`open`,`allowhtml`,`allowmycode`,`allowsmilies`,`allowimgcode`,`allowvideocode`,`allowpicons`,`allowtratings`,`usepostcounts`,`usethreadcounts`,`requireprefix`,`password`,`showinjump`,`style`,`overridestyle`,`rulestype`,`rulestitle`,`rules`,`defaultdatecut`,`defaultsortby`,`defaultsortorder`) VALUES ('Test','','','f',1,'',1,1,1,0,1,1,1,1,1,1,1,1,0,'',1,0,0,0,'','',0,'','')

![image](https://user-images.githubusercontent.com/4678120/83089055-5eeadc00-a0bb-11ea-89a0-33ccb0fdc254.png)

**Comment by zingaburga** [comment]
Thanks!  Hopefully the above fixes the issue.
