### ISSUE TITLE
Error with Mybb1806 with PHP7.1

### ISSUE THREAD

**Issue by Dr-The-One** [zingaburga/XThreads-MyBB-Plugin#26]
Dear Zingaburga,
Xthread 1.6.7 have error with PHP 7.1 with Mybb1806.
Below is the image.
It also remove custom thread fields.
Please help.
![xthread error](https://user-images.githubusercontent.com/31217951/83965034-69cd1a00-a8ce-11ea-8917-c60cb9ec1958.jpg)

**Comment by zingaburga** [comment]
Try updating to XThreads 1.68.
