### ISSUE TITLE
A lot of queries for prefixes

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#27]
I see in debug about 20+ queries for thread prefixes, something like this... every query about 3-6 ms...

Is possible to avoid somehow or improve anything?

![image](https://user-images.githubusercontent.com/778890/107418958-8ed9f280-6b17-11eb-946c-520e3b60e142.png)

@zingaburga

**Comment by zingaburga** [comment]
I don't believe XThreads even hooks there - are you sure this is caused by XThreads?

**Comment by Eldenroot** [comment]
I believe it is caused by Xthreads. Because all prefix IDs are used in forums where Xthrrads are used.

Is there any easy way how to debug and confirm?

**Comment by zingaburga** [comment]
XThreads does very little with thread prefixes in general, as that's predominantly a MyBB feature.

You could try something like this to find what functions are attached to the hook.  In inc/class_plugins.php, find

```
foreach($this->hooks[$hook] as $priority => $hooks)
```

add before

```
if($hook == 'forumdisplay_threadlist') die(var_dump($this->hooks[$hook]));
```

Then visit your forum page - it should dump anything attached to the hook.  Don't forget to delete the line afterwards.

**Comment by Eldenroot** [comment]
Hmm, you are right. It is caused by prefix filter plugin. I am sorry. Thank you for your help! Take care!
