### ISSUE TITLE
can't hide the cutomthread filed languages in the responsive theme ?

### ISSUE THREAD

**Issue by PARADOXP** [zingaburga/XThreads-MyBB-Plugin#28]
i have an issue with the custom thread filed languages...

i want to hide them in mobile view in a responsive theme... using media queries

```
@media only screen and (max-width: 768px) {
  coustomthreadfiled {
    display: none;
  }
}
```
here is an example of what i am trying to say.... 
![IMG_20210219_185254](https://user-images.githubusercontent.com/66396431/108510920-22b07900-72e5-11eb-9406-6a18fe319bf7.jpg)

the fields appeard in red boxes should be disappeared in responsive version...

but in the real thing is it cracked the responsive theme.

please suggest me how do i set this css value for the custom thread filed languages to hide them in responsive theme. not only one xthreads application but also in all xthread application.

Thank You

**Comment by zingaburga** [comment]
Sorry this is not a place to ask for support.

Please keep your question to the other places you asked:  
https://community.mybb.com/thread-231322.html  
http://mybbhacks.zingaburga.com/showthread.php?tid=11981
