### ISSUE TITLE
MyBB 1.8.27 compatibility issues?

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#29]
I did an upgrade to 1827, but first_post is not rendered in templates anymore....

**Comment by Sama34** [comment]
https://github.com/Sama34/XThreads-MyBB-Plugin/commit/e2259e6d66362cb4122da6eff9e4a7ad8b7782cd

**Comment by Eldenroot** [comment]
Your fix works fine! Thank you very much!!!

@Sama34 @zingaburga

**Comment by zingaburga** [comment]
Thanks!
