### ISSUE TITLE
Fatal error: Uncaught Error: Attempt to modify property "cache"

### ISSUE THREAD

**Issue by Eldenroot** [zingaburga/XThreads-MyBB-Plugin#31]
With specific settings in Google SEO plugin there is this fatal error during filtering:

`Fatal error: Uncaught Error: Attempt to modify property "cache" on null in [/path/to/my/board]/inc/xthreads/xt_forumdhooks.php:626`

**How to fix:**
Solution is to move the global $templates; declaration on line 609 of inc/xthreads/xt_forumdhooks.php up to line 597.
So that $templates is always available to line 626 below, not just when the Google SEO conditions test false.

Thx @lairdshaw for this report :)

@zingaburga

**Comment by zingaburga** [comment]
Thanks for reporting!
